### ISSUE TITLE
Incompatible with webpack-dev-server v4

### ISSUE THREAD

**Issue by MiloCasagrande** [DylanPiercey/spawn-server-webpack-plugin#25]
I just tested out webpack-dev-server v4, recently released, and spawn-server-webpack-plugin does not work anymore with that version.

Looks like the dev-server API change in incompatible ways:

https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

Glad to help put in case to update/test changes.

**Comment by DylanPiercey** [comment]
@MiloCasagrande if you want to take a stab at it that’d be awesome! Most likely if not it’ll take me a couple weeks or so to get to. IIRC I hacked this together to test with the beta version of the dev server and there are some simplifications that can be made.

Specifically the proxy-middleware module used under the hood now supports async targets which means the before hook can likely be removed and replaced with an async target.

**Comment by MiloCasagrande** [comment]
Maybe I can start looking at it by end of (this) week.

**Comment by DylanPiercey** [comment]
Just released a new major version which drops support for wds <= 3, but adds support for wds 4.

`spawn-server-webpack-plugin@6`
